Azure Privatelink documentation
redpanda-data/cloud-examples pull request #12
Opened 2024-07-31 23:06 UTC by chapmanc

This is a temporary set of instructions for customers to provision with private link and example terraform on how to connect to the redpanda cluster over private link.

2024-07-31 23:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/cloud-examples?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/cloud-examples?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/cloud-examples?pullRequest=12) it.</sub>

2024-08-02 10:50 UTC, gavinheavyside requested changes
A few nonblocking suggestions, but we should change the subscription IDs before merge.

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +To provision a redpanda with private link there is currently only API support with UX support coming soon.
suggestion, nonblocking: To provision a private Redpanda cluster with Private Link you must use the API. UI support is coming soon.

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +2. Next obtaion a client id and secret by going to Organizations in the Cloud UI. Navigate to Clients. Select or create a client you would like to use to create the network and cluster. You can copy
suggestion: ... by navigating to https://cloud.redpanda.com/clients. Select ...

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +    AZURE_SUBSCRIPTION_ID=60fc0bed-3072-4c53-906a-d130a934d520
blocking: use placeholder subscription IDs

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +    AZURE_PRIVATE_LINK_SUBSCRIPTION_ID=1b88eb19-4c80-4edd-870d-461e83ddcbb5
blocking: use placeholder subscription IDs

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +    "cidr_block": "10.0.0.0/20",
suggestion, nonblocking: the customer may not be using a 10.0.0.0 network, or `uksouth` region

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +    "redpanda_version": "24.1",
suggestion, nonblocking: This *might* be better as 24.2 by the time we merge

2024-08-02 10:50 UTC, gavinheavyside commented on customer-managed/azure/privatelink/README.md
> +    region = "uksouth"
suggestion, nonblocking: maybe we should define $REGION and $AZS to parameterize the example

2024-08-05 18:29 UTC, ncole commented
@gavinheavyside I updated for your comments.

2026-06-05 13:04 UTC, closed without merging